### ISSUE TITLE
Exercise 3 apic edit

### ISSUE THREAD

**Issue by ragsns** [ragsns/apichol#10]
To open the API Designer, on the command line enter:

apic edit

The Bluemix ID login just does not work for me.

Suggest using

SKIP_LOGIN=true apic edit

or can you help me fix the login via Bluemix?

**Comment by joshisa** [comment]
Not sure what the issue is for your login, but I agree that its probably safest to use the env var to avoid the issue completely for the general case.  Updated the exercise command ... so I consider this closed.
