### ISSUE TITLE
Various issues with ex4

### ISSUE THREAD

**Issue by ragsns** [ragsns/apichol#11]
First off, like your style of instructions. It seems very conversational.

Here's the yeah but (all rolled into one, hope you don't mind).

I never quite got connection of using the in-memory db. Does the javascript use the in memory db somewhere?

Some instructions are missing (like cd loopbackapp). In general, more instructions are better than assuming the attendees might know it (for example, not always is that hit <ctrl-c> on the process in the terminal window to terminate the process is included. It's there in some cases, not always).

Also you might want to ask attendees to cp the swagger.json to loopbackapp directory and kinda look at it and explain some salient parts (perhaps).

I am not sure looking at the JSON if it's calling the localhost or Bluemix.

The Models tab does not appear on Chrome. Seems fine on Safari and Firefox (but Firefox is slow).

The response to (at end)
http://localhost:3000/api/api/v1/mac/2
was a

{
"mac": null
}

I don't think it's correct and probably not a good idea to get back a null anyway?

Again, the no login apic edit might be better?

**Comment by ragsns** [comment]
The "mac": null may not be an issue. You may have to wait a bit for the application to warmup :-)

However, there are some edits that are needed including

If you're curious, we've also provided for reference and inspection, an uncommented copy in the ex4 directory. (../swagger-api-v-1.js.commented).

Some cleanup recommended (follow along true to script and you'll find the issues).

**Comment by joshisa** [comment]
Cleaned up ex4 quite a bit.  Filled in details, corrected some typos and added a summary section.  Went through the whole flow and things ran pretty smooth with no errors (at least on my mac).
