### ISSUE TITLE
Issues with Exercise 5 and 6

### ISSUE THREAD

**Issue by ragsns** [ragsns/apichol#12]
The standalone exercise 5 needs to be better integrated. Using a service is great, but, perhaps the goal here is

You might have an existing Data source that you want to front end with APIs, let's start by populating a data source - Employees in this exercise (exercise 5) an then make the data available via APIs, blah blah ...

I am hoping that the population can be done via Java/JDBC (our 24x7 HA application :-)).

**Comment by joshisa** [comment]
Population scripts now documented in ex5 via a Java class.  Added overview and summary sections (similar to ex2) to help strengthen integration point with DB CRUD API follow-on activity.
