### ISSUE TITLE
Flow

### ISSUE THREAD

**Issue by ragsns** [ragsns/apichol#13]
We need to look at the flow again once the exercises are better fleshed out but they seem to flow OK. Some repetitions which is good and a gradual progression.

In general within an exercise, we have to follow the cliched "say what we will say, say it, say what we said". 

We also need to connect exercises.

Can we all try to look at our exercises and try to improve the intra exercise flow, inter-exercise flow, etc.?

**Comment by svennam92** [comment]
Overall flow has been improved to reflect this
