### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by ragsns** [ragsns/apichol#14]
Java connection is at best tenuous. Not sure if we can fix this but let's brainstorm a bit more?

**Comment by joshisa** [comment]
Ex5 now has a Java Class that is compiled and used for the data population step.  Not sure if this is enough .. but it's a start 👍 .

**Comment by ragsns** [comment]
Agreed. It's a start.

I think it would be good to add some more. What I would like to do for the future version is create a Spring Boot app. with REST-based end points. i.e. instead of a simple CRUD API, do a bit more (unfortunately I don't think we've too much time to do this -- maybe if we get ambitious add this as an optional exercise or something).

**Comment by ragsns** [comment]
Sorry, keeping it opened

**Comment by svennam92** [comment]
No longer necessary as this is a generalized sample for API Connect
