### ISSUE TITLE
Problems with Bluemix login - ex6

### ISSUE THREAD

**Issue by ragsns** [ragsns/apichol#15]
I tried this again and don't seem to be able to login via my Bluemix creds. I use my creds and I see this window and that's it.

![image](https://cloud.githubusercontent.com/assets/655859/18457849/1e7ef406-792a-11e6-9679-5487b1e398c3.png)

We need to fix this ASAP (preferred) or find a workaround (acceptable).

Same results with different browsers.

**Comment by ragsns** [comment]
Based on http://www.ibm.com/support/knowledgecenter/SSFS6T/com.ibm.apic.toolkit.doc/tutorial_cli_project_stage_command.html

apic login --server us.apiconnect.ibmcloud.com
? Username: raghsrin@us.ibm.com
? Password (typing will be hidden) ********
Generate a passcode from https://login.ng.bluemix.net/UAALoginServerWAR/passcode
? Enter Bluemix one-time passcode: k8lnjb
Logged into us.apiconnect.ibmcloud.com successfully

This worked. Maybe include this in your instructions?

**Comment by ragsns** [comment]
Hmm. Still blocked since apic edit takes me back to the SSO screen where I can do nothing :-)

**Comment by ragsns** [comment]
On the Oracle VM this does not seem like an issue. On my mac (or on attendees mac) this might still be an issue.

**Comment by ragsns** [comment]
I updated the versions (just in case) but no improvement.

node --version
v4.5.0
[root@ragsns-linux ~]# npm -version
3.10.7
[root@ragsns-linux ~]# apic -v
API Connect: v5.0.3.0 iFix 1

**Comment by svennam92** [comment]
Problem resolved with new version of APIC
