### ISSUE TITLE
ex3

### ISSUE THREAD

**Issue by svennam92** [ragsns/apichol#19]
one section is labeled: `LoopBack API using API Designer`

However, it's not a LoopBack API, simply an Open API spec explorer and designer. LoopBack only applies when we connect the APIs to a LoopBack Node.js back-end, which we do in the next exercise.

After this exercise, you kind of think... "what was the point". It may be worth leading the user into the next step. Exercise 3 was simple api designing and management -- you need to create the backend yourself. So in exercise 4, we create that backend.

Could make a note that if you already have the backend, you could publish the swagger spec to Bluemix, where it would simply manage your existing APIs, like a typical API Management solution. Bluemix would provide analytics, gateway, security, authentication and user management.

**Comment by joshisa** [comment]
Updated ex3 to include a summary section that incorporates this feedback.  Feel free to reopen if you think it is still missing the mark.
