### ISSUE TITLE
empty file in this folder prevents `apic loopback` from working

### ISSUE THREAD

**Issue by svennam92** [ragsns/apichol#25]
can't have a .ignore file in here:
https://github.com/ragsns/apichol/tree/master/exercises/ex4/loopbackapp

Loopback complains that it needs an empty folder for the `apic loopback` command.

**Comment by joshisa** [comment]
Hrmmmph.   Needed a file in order to git add the folder itself.  Lemme delete and see if everything stays intact.  Otherwise, I'll update the steps to do a mkdir.

**Comment by joshisa** [comment]
ex4 instructions now contains steps to create the dir rather than having it already present.  Thanks for catching this.
