### ISSUE TITLE
Formatting issue?

### ISSUE THREAD

**Issue by ragsns** [ragsns/apichol#8]
Not sure if this is a formatting issue (or the intention of this?)

at

https://github.com/ragsns/apichol/tree/master/exercises/ex3

and

OpenAPI removes the guesswork in calling the service

Formatting could be improved?

**Comment by joshisa** [comment]
Used a blockquote for emphasis (hence its difference in format).  Tweaked the phrase to help clarify the emphasis ... "OpenAPI specs remove the guesswork in calling a given service" .  That said, if blockquotes are causing PDF problems ... I can remove it.

**Comment by joshisa** [comment]
Closing.  We can open a new issue if PDF gen has problems in our final run-throughs.
