### ISSUE TITLE
Improve the PDF Generation?

### ISSUE THREAD

**Issue by ragsns** [ragsns/apichol#9]
There is a section in the .md of exercise 3 which has

Browse to the spec. of the section that looks similar to:

The <pre>...</pre> fragment is skipped.

Workaround: Use the github URL in browser.

Or

a. option in pandoc to include the code in the <pre> ... </pre> blocks.
b. Screenshot it

I prefer b. But we need to find solution for a as well.

**Comment by ragsns** [comment]
I replaced <pre> with `and </pre> with` and massaged it around a bit and the PDF generation looked great, markdown display was just fine.

@joshisa if you agree, can we do this and close this?

**Comment by ragsns** [comment]
Sorry did not mean to close.

**Comment by joshisa** [comment]
I changed the pre tags to the backticks and updated the image urls that seemed to be busted.  I think this can be closed.
